#!/bin/bash

args=(
	--disable=missing-docstring
	--disable=duplicate-code
)

defaultFiles=*.py

for arg in "$@"; do

	if [[ -r $arg ]]; then
		# Assume a test name is given so we don't want to do discover.
		defaultFiles=
	fi
done

pylint "${args[@]}" "$@" $defaultFiles
